---
name: Build and Deploy React App to Surge.sh
on:
  push:
    branches: [main]
jobs:
  build:                           
    runs-on: ubuntu-latest 
    name: Deploying to surge 
    steps:    
    - uses: actions/checkout@v2 
    
    - name: Install Node.js
      uses: actions/setup-node@v2-beta
      with: 
        node-version: 16          
        - uses: borales/actions-yarn@v2.0.0 # `yarn install`
      with:
        cmd: install            
      
    - name: Build React App                              
      run: yarn build     
        
    - name: Clone index.html into 200.html                            
      run: cp build/index.html build/200.html

    - name: Install Surge
      run: npm install --global surge 

    - name: Run surge
      run: surge ./build christmas-exe-form.surge.sh --token ${{ secrets.SURGE_TOKEN }}